recoveries_server:
  ros__parameters:
    use_sim_time: False
    # Tema del mapa de costes en bruto para la comprobación de colisiones en el mapa de costes local.
    costmap_topic: local_costmap/costmap_raw
    # Tema para el footprint a en el marco local del mapa de costes.
    footprint_topic: local_costmap/published_footprint
    # Frecuencia para ejecutar plugins de comportamiento.
    cycle_frequency: 5.0
    # Plugins de recuperación
    recovery_plugins: ["backup","spin","wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    local_frame: odom
    global_frame: map
    robot_base_frame: robot_base_footprint
    transform_timeout: 0.1
    # Tiempo de anticipación de las colisiones (s).
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.5
    min_rotational_vel: 0.0
    rotational_acc_lim: 3.2